name: Run F1 Scraper and API

on:
  push:
    branches: [main]
  workflow_dispatch:  # Allows manual trigger from GitHub UI

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Chromium and ChromeDriver
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-browser chromium-chromedriver

    - name: Verify Chromium and ChromeDriver paths
      run: |
        which chromium-browser
        chromium-browser --version
        which chromedriver
        chromedriver --version

    - name: Run scraper and save data
      run: |
        python save_data.py  # make sure this script calls your save_data() function and creates data.json

    - name: Debug files in workspace
      run: ls -la

    - name: Show contents of data.json
      run: cat data.json

    - name: Configure git
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"

    - name: Checkout gh-pages branch or create it
      run: |
        git fetch origin gh-pages || true
        git checkout gh-pages || git checkout --orphan gh-pages

    - name: Copy data.json and commit
      run: |
        cp data.json ./data.json
        git add data.json
        git commit -m "Update scraped data" || echo "No changes to commit"

    - name: Push to gh-pages
      run: |
        git push origin gh-pages --force
